version: '3'
services:
  frontend:
    build:
      context: ./demo-angular-node
    ports:
      - "4200:80"
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
